#!/bin/sh

rm -f src/*.o src/*.so src/symbols.rds src/Makefile src/*.cmake src/CMakeCache.txt
rm -rf src/CMakefiles src/CPM_modules
rm inst/extdata/*transposed*
rm -rf src/_deps
rm -rf src/hwloc-prefix
rm -rf src/build
rm -f src/Makevars
rm -f src/Makevars.gen
rm -f src/*.so
rm -f src/*.a

# Restore Makevars.in if it was backed up
if [ -f src/Makevars.in.bak ]; then
  mv src/Makevars.in.bak src/Makevars.in
fi
